version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}
      - run: 
          name: Installing requirements
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install pytest==3.5.1
      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "venv"
  test:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}
      - run:
          name: Conducting tests
          command: |
            . venv/bin/activate
            python -m pytest
  deploy:
    docker:
      - image: <DOCKER_IMAGE>
#        environment:
#          <ENVIRONMENT_VARIABLES>
    working_directory: <WORKING_DIRECTORY>
    steps:
      - run:
          name: Deploy to AWS if tests pass and on master
          command: <command to deploy to aws>

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
