version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}
      - run: 
          name: Installing requirements
          command: |
            python -m venv venv
            . venv/bin/activate
            mkdir workspace
            pip install -r requirements.txt
            python writefile.py
      - persist-to-workspace:
          root: .
          paths: 
            - testfile.test
      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "venv"
  test:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/
      - restore_cache:
          key: deps1-{{ .Branch }}
      - run:
          name: Conducting tests
          command: |
            . venv/bin/activate
            python -m pytest
  deploy:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
          name: Test Deploy
          command: |
            python RandomModule.py

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test