version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.5
     steps:
       - checkout
       - run: 
           command: |
            python -m venv venv
            . venv/bin/activate
            pip install pytest
            python -m pytest