version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6.5
     steps:
       - checkout
       - restore_cache:
           key: deps1-{{ .Branch }}
       - run: 
           name: Install pytest
           command: |
            python -m venv venv
            . venv/bin/activate
            pip install pytest
       - save_cache:
           key: deps1-{{ .Branch }}
           paths:
             - "venv"
       - run:
           name: Conduct tests
           command: |
            . venv/bin/activate
            python -m pytest

           